"""Service for materializing SummaryContract to FHIR resources."""

import base64
from datetime import datetime
from typing import List, Dict, Any, Optional
import uuid
import json

from ..schemas.summary_contract import SummaryContract


def to_composition(
    contract: SummaryContract,
    patient_id: str,
    author_display: str = "Symphony AI"
) -> Dict[str, Any]:
    """Convert SummaryContract to FHIR Composition resource."""

    composition_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    # Create IPS-compliant narrative text with AI-generated content
    narrative_parts = [
        f"<h1>International Patient Summary</h1>",
        f"<p><strong>Patient:</strong> {patient_id}</p>",
        f"<p><strong>Generated by:</strong> {author_display} (AI-Generated Clinical Summary)</p>",
        f"<p><strong>Document Date:</strong> {timestamp}</p>",
        f"<p><em>This is an AI-generated International Patient Summary containing essential healthcare information for clinical decision-making in unplanned care scenarios.</em></p>"
    ]

    # Add overall clinical summary first
    if hasattr(contract, 'overall_narrative') and contract.overall_narrative:
        narrative_parts.extend([
            f"<h2>Clinical Summary</h2>",
            f"<p><strong>Overall Assessment:</strong> {contract.overall_narrative}</p>"
        ])

    # Add detailed section narratives
    if hasattr(contract, 'problems_narrative') and contract.problems_narrative:
        narrative_parts.extend([
            f"<h3>Active Problems and Diagnoses</h3>",
            f"<p>{contract.problems_narrative}</p>"
        ])

    if hasattr(contract, 'medications_narrative') and contract.medications_narrative:
        narrative_parts.extend([
            f"<h3>Current Medications</h3>",
            f"<p>{contract.medications_narrative}</p>"
        ])

    if hasattr(contract, 'allergies_narrative') and contract.allergies_narrative:
        narrative_parts.extend([
            f"<h3>Allergies and Intolerances</h3>",
            f"<p>{contract.allergies_narrative}</p>"
        ])

    if hasattr(contract, 'vitals_narrative') and contract.vitals_narrative:
        narrative_parts.extend([
            f"<h3>Vital Signs</h3>",
            f"<p>{contract.vitals_narrative}</p>"
        ])

    if hasattr(contract, 'labs_narrative') and contract.labs_narrative:
        narrative_parts.extend([
            f"<h3>Laboratory Results</h3>",
            f"<p>{contract.labs_narrative}</p>"
        ])

    if hasattr(contract, 'procedures_narrative') and contract.procedures_narrative:
        narrative_parts.extend([
            f"<h3>Procedures and Interventions</h3>",
            f"<p>{contract.procedures_narrative}</p>"
        ])

    if hasattr(contract, 'encounters_narrative') and contract.encounters_narrative:
        narrative_parts.extend([
            f"<h3>Recent Healthcare Encounters</h3>",
            f"<p>{contract.encounters_narrative}</p>"
        ])

    # Add care gaps and quality notes if available
    if hasattr(contract, 'care_gaps_narrative') and contract.care_gaps_narrative:
        narrative_parts.extend([
            f"<h3>Care Gaps and Recommendations</h3>",
            f"<p>{contract.care_gaps_narrative}</p>"
        ])

    # Fallback to basic listing if no AI narratives available
    if len(narrative_parts) <= 5:  # Only header elements
        narrative_parts.extend([
            "<h2>Summary Overview</h2>",
            "<p>This patient summary contains the following clinical information:</p>",
            "<ul>",
            f"    <li><strong>Active Problems:</strong> {len(contract.problems)} documented conditions</li>",
            f"    <li><strong>Current Medications:</strong> {len(contract.medications)} active prescriptions</li>",
            f"    <li><strong>Known Allergies:</strong> {len(contract.allergies)} documented allergies/intolerances</li>",
            f"    <li><strong>Recent Vital Signs:</strong> {len(contract.vitals)} measurements</li>",
            f"    <li><strong>Laboratory Results:</strong> {len(contract.labs)} recent tests</li>",
            f"    <li><strong>Procedures:</strong> {len(contract.procedures)} documented procedures</li>",
            f"    <li><strong>Healthcare Encounters:</strong> {len(contract.encounters)} recent visits</li>",
            "</ul>",
            "<p><em>Please refer to the structured sections below for detailed clinical information.</em></p>"
        ])

    narrative_html = f"""<div xmlns="http://www.w3.org/1999/xhtml">{''.join(narrative_parts)}</div>"""

    sections = []

    # Problems section
    if contract.problems:
        problem_entries = []
        for problem in contract.problems:
            if problem.provenance and "/" in problem.provenance:
                problem_entries.append({
                    "reference": problem.provenance
                })

        # Use AI narrative if available, otherwise fall back to list
        problems_text = ""
        if hasattr(contract, 'problems_narrative') and contract.problems_narrative:
            problems_text = f"<div xmlns='http://www.w3.org/1999/xhtml'><p>{contract.problems_narrative}</p><ul>{''.join([f'<li>{p.display}</li>' for p in contract.problems])}</ul></div>"
        else:
            problems_text = f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{p.display}</li>' for p in contract.problems])}</ul></div>"

        sections.append({
            "title": "Problems",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "11450-4",
                    "display": "Problem list"
                }]
            },
            "text": {
                "status": "generated",
                "div": problems_text
            },
            "entry": problem_entries if problem_entries else None
        })

    # Medications section
    if contract.medications:
        med_entries = []
        for med in contract.medications:
            if med.provenance and "/" in med.provenance:
                med_entries.append({
                    "reference": med.provenance
                })

        # Use AI narrative if available, otherwise fall back to list
        medications_text = ""
        if hasattr(contract, 'medications_narrative') and contract.medications_narrative:
            medications_text = f"<div xmlns='http://www.w3.org/1999/xhtml'><p>{contract.medications_narrative}</p><ul>{''.join([f'<li>{m.display}</li>' for m in contract.medications])}</ul></div>"
        else:
            medications_text = f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{m.display}</li>' for m in contract.medications])}</ul></div>"

        sections.append({
            "title": "Medications",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "10160-0",
                    "display": "History of medication use"
                }]
            },
            "text": {
                "status": "generated",
                "div": medications_text
            },
            "entry": med_entries if med_entries else None
        })

    # Allergies section
    if contract.allergies:
        allergy_entries = []
        for allergy in contract.allergies:
            if allergy.provenance and "/" in allergy.provenance:
                allergy_entries.append({
                    "reference": allergy.provenance
                })

        sections.append({
            "title": "Allergies",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "48765-2",
                    "display": "Allergies and adverse reactions"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{a.display}</li>' for a in contract.allergies])}</ul></div>"
            },
            "entry": allergy_entries if allergy_entries else None
        })

    # Vitals section
    if contract.vitals:
        vital_entries = []
        for vital in contract.vitals:
            if vital.provenance and "/" in vital.provenance:
                vital_entries.append({
                    "reference": vital.provenance
                })

        sections.append({
            "title": "Vitals",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "8716-3",
                    "display": "Vital signs"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{v.display}: {v.value}</li>' for v in contract.vitals])}</ul></div>"
            },
            "entry": vital_entries if vital_entries else None
        })

    # Key Labs section
    if contract.labs:
        lab_entries = []
        for lab in contract.labs:
            if lab.provenance and "/" in lab.provenance:
                lab_entries.append({
                    "reference": lab.provenance
                })

        sections.append({
            "title": "Key Labs",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "30954-2",
                    "display": "Relevant diagnostic tests/laboratory data"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{l.display}: {l.value}</li>' for l in contract.labs])}</ul></div>"
            },
            "entry": lab_entries if lab_entries else None
        })

    # Procedures section
    if contract.procedures:
        proc_entries = []
        for proc in contract.procedures:
            if proc.provenance and "/" in proc.provenance:
                proc_entries.append({
                    "reference": proc.provenance
                })

        sections.append({
            "title": "Procedures",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "47519-4",
                    "display": "History of procedures"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{p.display}</li>' for p in contract.procedures])}</ul></div>"
            },
            "entry": proc_entries if proc_entries else None
        })

    # Encounters section
    if contract.encounters:
        encounter_entries = []
        for encounter in contract.encounters:
            if encounter.provenance and "/" in encounter.provenance:
                encounter_entries.append({
                    "reference": encounter.provenance
                })

        sections.append({
            "title": "Encounters",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "46240-8",
                    "display": "History of encounters"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{e.display}</li>' for e in contract.encounters])}</ul></div>"
            },
            "entry": encounter_entries if encounter_entries else None
        })

    # Care Gaps section
    if contract.careGaps:
        sections.append({
            "title": "Care Gaps",
            "code": {
                "coding": [{
                    "system": "http://example.org/ai-sections",
                    "code": "care-gaps",
                    "display": "Identified care gaps"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{gap}</li>' for gap in contract.careGaps])}</ul></div>"
            }
        })

    # Data Quality Notes section
    if contract.dataQualityNotes:
        sections.append({
            "title": "Data Quality Notes",
            "code": {
                "coding": [{
                    "system": "http://example.org/ai-sections",
                    "code": "data-quality",
                    "display": "Data quality observations"
                }]
            },
            "text": {
                "status": "generated",
                "div": f"<div xmlns='http://www.w3.org/1999/xhtml'><ul>{''.join([f'<li>{note}</li>' for note in contract.dataQualityNotes])}</ul></div>"
            }
        })

    composition = {
        "resourceType": "Composition",
        "id": composition_id,
        "meta": {
            "profile": ["http://hl7.org/fhir/uv/ips/StructureDefinition/Composition-uv-ips"]
        },
        "status": "final",
        "type": {
            "coding": [{
                "system": "http://loinc.org",
                "code": "60591-5",
                "display": "Patient summary Document"
            }],
            "text": "International Patient Summary"
        },
        "category": [{
            "coding": [{
                "system": "http://loinc.org",
                "code": "11369-6",
                "display": "History of Immunization Narrative"
            }]
        }],
        "subject": {
            "reference": f"Patient/{patient_id}"
        },
        "date": timestamp,
        "author": [{
            "display": author_display
        }],
        "title": "AI-Generated International Patient Summary",
        "confidentiality": "N",
        "text": {
            "status": "generated",
            "div": narrative_html
        },
        "section": [s for s in sections if s.get("entry") or s.get("text")]
    }

    return composition


def to_lists(
    contract: SummaryContract,
    patient_id: str,
    author_display: str = "Symphony AI"
) -> List[Dict[str, Any]]:
    """Convert SummaryContract to FHIR List resources."""

    lists = []
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    # Problem List
    if contract.problems:
        problem_entries = []
        for problem in contract.problems:
            if problem.provenance and "/" in problem.provenance:
                problem_entries.append({
                    "item": {
                        "reference": problem.provenance
                    }
                })

        lists.append({
            "resourceType": "List",
            "id": str(uuid.uuid4()),
            "status": "current",
            "mode": "snapshot",
            "title": "Problem List",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "11450-4",
                    "display": "Problem list"
                }]
            },
            "subject": {
                "reference": f"Patient/{patient_id}"
            },
            "date": timestamp,
            "source": {
                "display": author_display
            },
            "entry": problem_entries
        })

    # Medication List
    if contract.medications:
        med_entries = []
        for med in contract.medications:
            if med.provenance and "/" in med.provenance:
                med_entries.append({
                    "item": {
                        "reference": med.provenance
                    }
                })

        lists.append({
            "resourceType": "List",
            "id": str(uuid.uuid4()),
            "status": "current",
            "mode": "snapshot",
            "title": "Medication List",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "10160-0",
                    "display": "History of medication use"
                }]
            },
            "subject": {
                "reference": f"Patient/{patient_id}"
            },
            "date": timestamp,
            "source": {
                "display": author_display
            },
            "entry": med_entries
        })

    # Allergy List
    if contract.allergies:
        allergy_entries = []
        for allergy in contract.allergies:
            if allergy.provenance and "/" in allergy.provenance:
                allergy_entries.append({
                    "item": {
                        "reference": allergy.provenance
                    }
                })

        lists.append({
            "resourceType": "List",
            "id": str(uuid.uuid4()),
            "status": "current",
            "mode": "snapshot",
            "title": "Allergy List",
            "code": {
                "coding": [{
                    "system": "http://loinc.org",
                    "code": "48765-2",
                    "display": "Allergies and adverse reactions"
                }]
            },
            "subject": {
                "reference": f"Patient/{patient_id}"
            },
            "date": timestamp,
            "source": {
                "display": author_display
            },
            "entry": allergy_entries
        })

    return lists


def to_document_reference(
    contract: SummaryContract,
    patient_id: str,
    author_display: str = "Symphony AI",
    pdf_bytes: Optional[bytes] = None,
    tags: Optional[List[str]] = None
) -> Dict[str, Any]:
    """Convert SummaryContract to FHIR DocumentReference resource."""

    doc_ref_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    # Create markdown content
    newline = '\n'
    problems_list = ''.join([f'- {p.display}{newline}' for p in contract.problems]) if contract.problems else f'None documented{newline}'
    medications_list = ''.join([f'- {m.display} ({m.status or "unknown status"}){newline}' for m in contract.medications]) if contract.medications else f'None documented{newline}'
    allergies_list = ''.join([f'- {a.display}{newline}' for a in contract.allergies]) if contract.allergies else f'None documented{newline}'
    vitals_list = ''.join([f'- {v.display}: {v.value}{newline}' for v in contract.vitals]) if contract.vitals else f'None documented{newline}'
    labs_list = ''.join([f'- {l.display}: {l.value}{newline}' for l in contract.labs]) if contract.labs else f'None documented{newline}'
    procedures_list = ''.join([f'- {p.display}{newline}' for p in contract.procedures]) if contract.procedures else f'None documented{newline}'
    encounters_list = ''.join([f'- {e.display} ({e.type}){newline}' for e in contract.encounters]) if contract.encounters else f'None documented{newline}'
    care_gaps_list = ''.join([f'- {gap}{newline}' for gap in contract.careGaps]) if contract.careGaps else f'None identified{newline}'
    quality_notes_list = ''.join([f'- {note}{newline}' for note in contract.dataQualityNotes]) if contract.dataQualityNotes else f'No issues noted{newline}'

    markdown_content = f"""# AI Clinical Summary

**Patient:** {patient_id}
**Generated by:** {author_display}
**Date:** {timestamp}

## Problems ({len(contract.problems)})
{problems_list}
## Medications ({len(contract.medications)})
{medications_list}
## Allergies ({len(contract.allergies)})
{allergies_list}
## Vitals ({len(contract.vitals)})
{vitals_list}
## Key Labs ({len(contract.labs)})
{labs_list}
## Procedures ({len(contract.procedures)})
{procedures_list}
## Encounters ({len(contract.encounters)})
{encounters_list}
## Care Gaps ({len(contract.careGaps)})
{care_gaps_list}
## Data Quality Notes ({len(contract.dataQualityNotes)})
{quality_notes_list}"""

    # Create PDF content (placeholder if no bytes provided)
    if pdf_bytes is None:
        # Create a minimal placeholder PDF-like content
        placeholder_content = f"Symphony AI Clinical Summary - Patient {patient_id} - Generated {timestamp}"
        pdf_bytes = base64.b64encode(placeholder_content.encode('utf-8')).decode('utf-8')
    else:
        pdf_bytes = base64.b64encode(pdf_bytes).decode('utf-8')

    # Prepare category with tags
    category = []
    if tags:
        for tag in tags:
            category.append({
                "coding": [{
                    "system": "http://example.org/ai-tags",
                    "code": tag.lower().replace(" ", "-"),
                    "display": tag
                }]
            })

    # Add default AI category
    category.append({
        "coding": [{
            "system": "http://hl7.org/fhir/document-reference-category",
            "code": "clinical-note",
            "display": "Clinical Note"
        }]
    })

    document_reference = {
        "resourceType": "DocumentReference",
        "id": doc_ref_id,
        "status": "current",
        "type": {
            "coding": [{
                "system": "http://loinc.org",
                "code": "11488-4",
                "display": "Consult note"
            }],
            "text": "AI Clinical Note"
        },
        "category": category,
        "subject": {
            "reference": f"Patient/{patient_id}"
        },
        "date": timestamp,
        "author": [{
            "display": author_display
        }],
        "description": "AI-generated clinical summary with structured data extraction",
        "content": [
            {
                "attachment": {
                    "contentType": "text/markdown",
                    "data": base64.b64encode(markdown_content.encode('utf-8')).decode('utf-8'),
                    "title": f"Clinical Summary - {patient_id}"
                }
            },
            {
                "attachment": {
                    "contentType": "application/pdf",
                    "data": pdf_bytes,
                    "title": f"Clinical Summary PDF - {patient_id}"
                }
            }
        ]
    }

    # Add AI tags extension if provided
    if tags:
        document_reference["extension"] = [{
            "url": "http://example.org/fhir/extension/ai-tags",
            "valueString": ", ".join(tags)
        }]

    return document_reference


def make_provenance(
    target_refs: List[str],
    source_bundle_ref: Optional[str] = None,
    author_display: str = "Symphony AI"
) -> Dict[str, Any]:
    """Create FHIR Provenance resource for generated summary resources."""

    provenance_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    provenance = {
        "resourceType": "Provenance",
        "id": provenance_id,
        "target": [{"reference": ref} for ref in target_refs],
        "occurredDateTime": timestamp,
        "recorded": timestamp,
        "activity": {
            "coding": [{
                "system": "http://terminology.hl7.org/CodeSystem/v3-DataOperation",
                "code": "DERIVE",
                "display": "derive"
            }]
        },
        "agent": [{
            "type": {
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
                    "code": "performer",
                    "display": "Performer"
                }]
            },
            "who": {
                "display": author_display
            }
        }]
    }

    # Add source entity if bundle reference provided
    if source_bundle_ref:
        provenance["entity"] = [{
            "role": "source",
            "what": {
                "reference": source_bundle_ref
            }
        }]

    return provenance


def create_summary_bundle(
    contract: SummaryContract,
    patient_id: str,
    method: str = "composition",
    author_display: str = "Symphony AI",
    pdf_bytes: Optional[bytes] = None,
    doc_ref_tags: Optional[List[str]] = None,
    source_bundle_ref: Optional[str] = None
) -> Dict[str, Any]:
    """Create a transaction bundle with materialized summary resources."""

    bundle_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.%fZ")

    entries = []
    target_refs = []

    if method in ["composition", "all"]:
        composition = to_composition(contract, patient_id, author_display)
        entries.append({
            "resource": composition,
            "request": {
                "method": "PUT",
                "url": f"Composition/{composition['id']}"
            }
        })
        target_refs.append(f"Composition/{composition['id']}")

    if method in ["lists", "all"]:
        lists = to_lists(contract, patient_id, author_display)
        for list_resource in lists:
            entries.append({
                "resource": list_resource,
                "request": {
                    "method": "PUT",
                    "url": f"List/{list_resource['id']}"
                }
            })
            target_refs.append(f"List/{list_resource['id']}")

    if method in ["document", "all"]:
        doc_ref = to_document_reference(contract, patient_id, author_display, pdf_bytes, doc_ref_tags)
        entries.append({
            "resource": doc_ref,
            "request": {
                "method": "PUT",
                "url": f"DocumentReference/{doc_ref['id']}"
            }
        })
        target_refs.append(f"DocumentReference/{doc_ref['id']}")

    # Always create provenance
    provenance = make_provenance(target_refs, source_bundle_ref, author_display)
    entries.append({
        "resource": provenance,
        "request": {
            "method": "PUT",
            "url": f"Provenance/{provenance['id']}"
        }
    })

    bundle = {
        "resourceType": "Bundle",
        "id": bundle_id,
        "type": "transaction",
        "timestamp": timestamp,
        "entry": entries
    }

    return bundle